// <auto-generated />
using CrudReact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudReact.Migrations
{
    [DbContext(typeof(DBContextProductos))]
    partial class DBContextProductosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudReact.Models.Almacenes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ubicacion")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("CrudReact.Models.Empleados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("departamento")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("CrudReact.Models.Productos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fecha_venc")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("descripcion")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("CrudReact.Models.Sucursales", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ubicacion")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
